### ISSUE TITLE
RFI-14 As a user i want to display and search a solution having setted by default the today's date

### ISSUE THREAD

**Issue by gstaiano** [d3vsupp0r7/android#33]
In most cases, the user not set the date for searching a solution. This story will discover the possibility to add by default the system date in order to search a solution without pressing the calendar button and select a proper date.

**Comment by gstaiano** [comment]
Resolved in #36

**Comment by d3vsupp0r7** [comment]
As user experience we need to add the the current date on "date" button on application login,  in order to not confuse the user on the journey search scenario
